# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 0999
  host: localhost
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ninesfi_dev

test:
  <<: *default
  database: ninesfi_test
#
production:
  primary: &primary_production
    <<: *default
    database: ninesfi_tracker_api_production
    username: ninesfi_tracker_api
    password: <%= ENV["NINESFI_TRACKER_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ninesfi_tracker_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ninesfi_tracker_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ninesfi_tracker_api_production_cable
    migrations_paths: db/cable_migrate
